<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>MphRead</RootNamespace>
    <AssemblyName>ProjectPrimeEnhancedMaterials</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Client/Client.csproj" />
    <ProjectReference Include="../Renderer/Renderer.csproj" />
  </ItemGroup>
</Project>
