using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using OpenTK.Mathematics;

namespace MphRead
{
    public enum RoomSize : uint
    {
        None = 0,
        Small = 2,
        Medium = 3,
        Large = 4,
        SinglePlayer = 6
    }

    public class RoomMetadata
    {
        public int Id { get; }
        public string Name { get; }
        public string? InGameName { get; }
        public string Archive { get; }
        public string ModelPath { get; }
        public string AnimationPath { get; }
        public string CollisionPath { get; }
        public string? TexturePath { get; }
        public string? EntityPath { get; }
        public string? EntityFilename { get; }
        public string? NodePath { get; }
        public string? RoomNodeName { get; }
        public uint BattleTimeLimit { get; }
        public uint TimeLimit { get; }
        public short PointLimit { get; }
        public short NodeLayer { get; }
        public bool FogEnabled { get; }
        // future?: currently only used to set the clear color for FH rooms
        public bool ClearFog { get; }
        public ColorRgb FogColor { get; }
        public int FogSlope { get; }
        public int FogOffset { get; }
        public float FarClip { get; }
        public int FarClipInt { get; }
        public ColorRgb Light1Color { get; }
        public Vector3 Light1Vector { get; }
        public ColorRgb Light2Color { get; }
        public Vector3 Light2Vector { get; }
        public float KillHeight { get; }
        public RoomSize Size { get; }
        public bool Multiplayer { get; }
        public bool FirstHunt { get; }
        public bool Hybrid { get; }
        public Vector3 CameraMin { get; }
        public Vector3 CameraMax { get; }
        public Vector3 PlayerMin { get; }
        public Vector3 PlayerMax { get; }
        public bool HasLimits { get; }

        public RoomMetadata(int id, string name, string? inGameName, string archive, string modelPath, string animationPath,
            string collisionPath, string? texturePath, string? entityPath, string? nodePath, string? roomNodeName, uint battleTimeLimit,
            uint timeLimit, short pointLimit, short nodeLayer, bool fogEnabled, bool clearFog, ColorRgb fogColor, int fogSlope,
            ushort fogOffset, ColorRgb light1Color, Vector3 light1Vector, ColorRgb light2Color, Vector3 light2Vector, int farClip,
            int killHeight, RoomSize size, Vector3 cameraMin = default, Vector3 cameraMax = default, Vector3 playerMin = default,
            Vector3 playerMax = default, bool multiplayer = false, bool firstHunt = false, bool hybrid = false)
        {
            Id = id;
            Name = name;
            InGameName = inGameName;
            Archive = archive;
            if (firstHunt || hybrid)
            {
                ModelPath = $@"levels\models\{modelPath}";
                AnimationPath = $@"levels\models\{animationPath}";
                CollisionPath = $@"levels\collision\{collisionPath}";
            }
            else
            {
                ModelPath = $@"_archives\{archive}\{modelPath}";
                AnimationPath = $@"_archives\{archive}\{animationPath}";
                CollisionPath = $@"_archives\{archive}\{collisionPath}";
            }
            TexturePath = texturePath == null ? null : $@"levels\textures\{texturePath}";
            EntityFilename = entityPath;
            EntityPath = entityPath == null ? null : $@"levels\entities\{entityPath}";
            NodePath = nodePath == null ? null : $@"levels\nodeData\{nodePath}";
            RoomNodeName = roomNodeName;
            BattleTimeLimit = battleTimeLimit;
            TimeLimit = timeLimit;
            PointLimit = pointLimit;
            NodeLayer = nodeLayer;
            FogEnabled = fogEnabled;
            ClearFog = clearFog;
            FogColor = fogColor;
            FogSlope = fogSlope;
            FogOffset = fogOffset & 0x7FFF;
            Light1Color = light1Color;
            Light1Vector = light1Vector.Normalized();
            Light2Color = light2Color;
            Light2Vector = light2Vector.Normalized();
            Multiplayer = multiplayer;
            FarClip = Fixed.ToFloat(farClip);
            FarClipInt = farClip;
            KillHeight = Fixed.ToFloat(killHeight);
            Size = size;
            CameraMin = cameraMin;
            CameraMax = cameraMax;
            PlayerMin = playerMin;
            PlayerMax = playerMax;
            FirstHunt = firstHunt;
            Hybrid = hybrid;
            HasLimits = cameraMin != Vector3.Zero || cameraMax != Vector3.Zero
                || playerMin != Vector3.Zero || playerMax != Vector3.Zero;
        }
    }

    public static partial class Metadata
    {
        // Global IDs are wire/content identities, not indices in the retained catalog.
        // First Hunt metadata keeps its separate local IDs; custom IDs begin at 138.
        private static readonly IReadOnlyDictionary<int, string> _baseRoomIds
            = new Dictionary<int, string>()
            {
                [93] = "MP1 SANCTORUS",
                [94] = "MP2 HARVESTER",
                [95] = "MP3 PROVING GROUND",
                [96] = "MP4 HIGHGROUND - EXPANDED",
                [97] = "MP4 HIGHGROUND",
                [98] = "MP5 FUEL SLUICE",
                [99] = "MP6 HEADSHOT",
                [100] = "MP7 PROCESSOR CORE",
                [101] = "MP8 FIRE CONTROL",
                [102] = "MP9 CRYOCHASM",
                [103] = "MP10 OVERLOAD",
                [104] = "MP11 BREAKTHROUGH",
                [105] = "MP12 SIC TRANSIT",
                [106] = "MP13 ACCELERATOR",
                [107] = "MP14 OUTER REACH",
                [108] = "CTF1 FAULT LINE - EXPANDED",
                [109] = "CTF1_FAULT LINE",
                [110] = "AD1 TRANSFER LOCK BT",
                [111] = "AD1 TRANSFER LOCK DM",
                [112] = "AD2 MAGMA VENTS",
                [113] = "AD2 ALINOS PERCH",
                [114] = "UNIT1 ALINOS LANDFALL",
                [115] = "UNIT2 LANDING BAY",
                [116] = "UNIT 3 VESPER STARPORT",
                [117] = "UNIT 4 ARCTERRA BASE",
                [118] = "Gorea Prison",
                [119] = "E3 FIRST HUNT",
                [122] = "biodefense chamber 06",
                [123] = "biodefense chamber 05",
                [124] = "biodefense chamber 03",
                [125] = "biodefense chamber 08",
                [126] = "biodefense chamber 04",
                [127] = "biodefense chamber 07",
                [128] = "Level MP1",
                [129] = "Level MP2",
                [130] = "Level MP3",
                [135] = "Level MP5",
                [136] = "Level MP1b",
                [137] = "E3 level",
            };

        private static IReadOnlyDictionary<int, string> RoomIds
            => RuntimeRooms.Snapshot.Rooms.ToDictionary(room => room.RuntimeId,
                room => room.RoomKey);

        private static readonly IReadOnlyList<RoomMetadata> BaseRoomList
            = new List<RoomMetadata>()
        {
            new RoomMetadata(
                id: 93,
                name: "MP1 SANCTORUS",
                inGameName: "Data Shrine",
                archive: "mp1",
                modelPath: "mp1_Model.bin",
                animationPath: "mp1_Anim.bin",
                collisionPath: "mp1_Collision.bin",
                texturePath: "mp1_tex.bin",
                entityPath: "mp1_Ent.bin",
                nodePath: "mp1_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(18, 31, 18),
                fogSlope: 4,
                fogOffset: 65152,
                light1Color: new ColorRgb(24, 31, 24),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(7, 11, 15),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 368640,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 94,
                name: "MP2 HARVESTER",
                inGameName: "Harvester",
                archive: "mp2",
                modelPath: "mp2_model.bin",
                animationPath: "mp2_anim.bin",
                collisionPath: "mp2_collision.bin",
                texturePath: "mp2_tex.bin",
                entityPath: "mp2_Ent.bin",
                nodePath: "mp2_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: true,
                fogColor: new ColorRgb(25, 30, 20),
                fogSlope: 4,
                fogOffset: 65152,
                light1Color: new ColorRgb(25, 30, 20),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 11, 6),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 3072000,
                killHeight: 4096,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-167936, 24576, -294912).ToFloatVector(),
                cameraMax: new Vector3Fx(167936, 131072, 294912).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 95,
                name: "MP3 PROVING GROUND",
                inGameName: "Combat Hall",
                archive: "mp3",
                modelPath: "mp3_Model.bin",
                animationPath: "mp3_Anim.bin",
                collisionPath: "mp3_Collision.bin",
                texturePath: "mp3_Tex.bin",
                entityPath: "mp3_Ent.bin",
                nodePath: "mp3_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(31, 24, 18),
                fogSlope: 5,
                fogOffset: 65180,
                light1Color: new ColorRgb(31, 24, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(13, 12, 7),
                light2Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                farClip: 1433600,
                killHeight: -122880,
                size: RoomSize.Small,
                cameraMin: new Vector3Fx(-45056, 0, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(40960, 53248, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 96,
                name: "MP4 HIGHGROUND - EXPANDED",
                inGameName: "Elder Passage",
                archive: "mp4",
                modelPath: "mp4_model.bin",
                animationPath: "mp4_anim.bin",
                collisionPath: "mp4_collision.bin",
                texturePath: "mp4_Tex.bin",
                entityPath: "mp4_Ent.bin",
                nodePath: "mp4_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(12, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(31, 24, 18),
                fogSlope: 5,
                fogOffset: 65200,
                light1Color: new ColorRgb(31, 24, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(13, 12, 7),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1687552,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-151552, -4096, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(184320, 102400, 81920).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 97,
                name: "MP4 HIGHGROUND",
                inGameName: "High Ground",
                archive: "unit1_RM1",
                modelPath: "unit1_RM1_model.bin",
                animationPath: "unit1_RM1_anim.bin",
                collisionPath: "unit1_RM1_collision.bin",
                texturePath: "unit1_rm1_tex.bin",
                entityPath: "mp4_dm1_Ent.bin",
                nodePath: "mp4_dm1_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(12, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(31, 24, 18),
                fogSlope: 5,
                fogOffset: 65200,
                light1Color: new ColorRgb(31, 24, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(13, 12, 7),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1740800,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-151552, -4096, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(184320, 102400, 81920).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 98,
                name: "MP5 FUEL SLUICE",
                inGameName: "Compression Chamber",
                archive: "mp5",
                modelPath: "mp5_Model.bin",
                animationPath: "mp5_Anim.bin",
                collisionPath: "mp5_Collision.bin",
                texturePath: "mp5_tex.bin",
                entityPath: "mp5_Ent.bin",
                nodePath: "mp5_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(20, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(24, 20, 31),
                fogSlope: 3,
                fogOffset: 65152,
                light1Color: new ColorRgb(18, 22, 30),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 8, 14),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Small,
                cameraMin: new Vector3Fx(-98304, 0, -57344).ToFloatVector(),
                cameraMax: new Vector3Fx(110592, 69632, 57344).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 99,
                name: "MP6 HEADSHOT",
                inGameName: "Head Shot",
                archive: "mp6",
                modelPath: "mp6_model.bin",
                animationPath: "mp6_anim.bin",
                collisionPath: "mp6_collision.bin",
                texturePath: "mp6_tex.bin",
                entityPath: "mp6_Ent.bin",
                nodePath: "mp6_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(20, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(24, 20, 31),
                fogSlope: 3,
                fogOffset: 65152,
                light1Color: new ColorRgb(18, 22, 30),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 8, 14),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 5734400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-200704, 0, -200704).ToFloatVector(),
                cameraMax: new Vector3Fx(196608, 196608, 192512).ToFloatVector(),
                playerMin: new Vector3Fx(-286720, -86949, -286720).ToFloatVector(),
                playerMax: new Vector3Fx(286720, 196608, 286720).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 100,
                name: "MP7 PROCESSOR CORE",
                inGameName: "Processor Core",
                archive: "mp7",
                modelPath: "mp7_model.bin",
                animationPath: "mp7_anim.bin",
                collisionPath: "mp7_collision.bin",
                texturePath: "mp7_tex.bin",
                entityPath: "mp7_Ent.bin",
                nodePath: "mp7_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(20, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(31, 18, 6),
                fogSlope: 6,
                fogOffset: 65300,
                light1Color: new ColorRgb(31, 18, 6),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(13, 6, 4),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 819200,
                killHeight: -122880,
                size: RoomSize.Small,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 101,
                name: "MP8 FIRE CONTROL",
                inGameName: "Weapons Complex",
                archive: "mp8",
                modelPath: "mp8_model.bin",
                animationPath: "mp8_anim.bin",
                collisionPath: "mp8_collision.bin",
                texturePath: "mp8_Tex.bin",
                entityPath: "mp8_Ent.bin",
                nodePath: "mp8_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(20, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 50,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(20, 24, 31),
                fogSlope: 3,
                fogOffset: 65152,
                light1Color: new ColorRgb(18, 22, 30),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 8, 14),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 4096000,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-176128, 0, -135168).ToFloatVector(),
                cameraMax: new Vector3Fx(180224, 135168, 225280).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 102,
                name: "MP9 CRYOCHASM",
                inGameName: "Ice Hive",
                archive: "mp9",
                modelPath: "mp9_model.bin",
                animationPath: "mp9_anim.bin",
                collisionPath: "mp9_collision.bin",
                texturePath: "mp9_tex.bin",
                entityPath: "mp9_Ent.bin",
                nodePath: "mp9_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(12, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(20, 27, 31),
                fogSlope: 5,
                fogOffset: 65152,
                light1Color: new ColorRgb(20, 27, 31),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(8, 8, 15),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 327680,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 103,
                name: "MP10 OVERLOAD",
                inGameName: "Incubation Vault",
                archive: "mp10",
                modelPath: "mp10_model.bin",
                animationPath: "mp10_anim.bin",
                collisionPath: "mp10_collision.bin",
                texturePath: "mp10_tex.bin",
                entityPath: "mp10_Ent.bin",
                nodePath: "mp10_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(20, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(18, 31, 18),
                fogSlope: 5,
                fogOffset: 65152,
                light1Color: new ColorRgb(24, 31, 24),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(7, 11, 15),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 409600,
                killHeight: -122880,
                size: RoomSize.Small,
                cameraMin: new Vector3Fx(-90112, -8192, -61440).ToFloatVector(),
                cameraMax: new Vector3Fx(73728, 54476, 45056).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 104,
                name: "MP11 BREAKTHROUGH",
                inGameName: "Sanctorus",
                archive: "mp11",
                modelPath: "mp11_model.bin",
                animationPath: "mp11_anim.bin",
                collisionPath: "mp11_collision.bin",
                texturePath: "mp11_tex.bin",
                entityPath: "mp11_Ent.bin",
                nodePath: "mp11_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(16, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(20, 27, 31),
                fogSlope: 5,
                fogOffset: 65152,
                light1Color: new ColorRgb(20, 27, 31),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(8, 8, 15),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 409600,
                killHeight: -122880,
                size: RoomSize.Small,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 105,
                name: "MP12 SIC TRANSIT",
                inGameName: "Sic Transit",
                archive: "mp12",
                modelPath: "mp12_model.bin",
                animationPath: "mp12_anim.bin",
                collisionPath: "mp12_collision.bin",
                texturePath: "mp12_Tex.bin",
                entityPath: "mp12_Ent.bin",
                nodePath: "mp12_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(16, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(10, 14, 18),
                fogSlope: 6,
                fogOffset: 65300,
                light1Color: new ColorRgb(10, 14, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(4, 4, 8),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 819200,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-77824, -4096, -118784).ToFloatVector(),
                cameraMax: new Vector3Fx(110592, 61440, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 106,
                name: "MP13 ACCELERATOR",
                inGameName: "Fuel Stack",
                archive: "mp13",
                modelPath: "mp13_model.bin",
                animationPath: "mp13_anim.bin",
                collisionPath: "mp13_collision.bin",
                texturePath: "mp13_tex.bin",
                entityPath: "mp13_Ent.bin",
                nodePath: "mp13_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(16, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(24, 20, 31),
                fogSlope: 3,
                fogOffset: 65152,
                light1Color: new ColorRgb(18, 22, 30),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 8, 14),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-94208, -118784, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(167936, 122880, 172032).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 107,
                name: "MP14 OUTER REACH",
                inGameName: "Outer Reach",
                archive: "mp14",
                modelPath: "mp14_model.bin",
                animationPath: "mp14_anim.bin",
                collisionPath: "mp14_collision.bin",
                texturePath: "mp14_tex.bin",
                entityPath: "mp14_Ent.bin",
                nodePath: "mp14_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(16, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 0,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(24, 20, 31),
                fogSlope: 4,
                fogOffset: 65152,
                light1Color: new ColorRgb(24, 20, 31),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 8, 14),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 4915200,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-131072, -14745, -122880).ToFloatVector(),
                cameraMax: new Vector3Fx(126976, 98304, 118784).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 108,
                name: "CTF1 FAULT LINE - EXPANDED",
                inGameName: "Fault Line",
                archive: "ctf1",
                modelPath: "ctf1_model.bin",
                animationPath: "ctf1_anim.bin",
                collisionPath: "ctf1_collision.bin",
                texturePath: "ctf1_tex.bin",
                entityPath: "ctf1_Ent.bin",
                nodePath: "ctf1_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 5,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(10, 14, 18),
                fogSlope: 6,
                fogOffset: 65300,
                light1Color: new ColorRgb(10, 14, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(4, 4, 8),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-294912, 0, -106496).ToFloatVector(),
                cameraMax: new Vector3Fx(286720, 96256, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 109,
                name: "CTF1_FAULT LINE",
                inGameName: "Subterranean",
                archive: "unit4_rm5",
                modelPath: "unit4_rm5_model.bin",
                animationPath: "unit4_rm5_anim.bin",
                collisionPath: "unit4_rm5_collision.bin",
                texturePath: "unit4_rm5_tex.bin",
                entityPath: "ctf1_dm1_Ent.bin",
                nodePath: "ctf1_dm1_NODE.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 5,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(10, 14, 18),
                fogSlope: 6,
                fogOffset: 65300,
                light1Color: new ColorRgb(10, 14, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(4, 4, 8),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-294912, 0, -106496).ToFloatVector(),
                cameraMax: new Vector3Fx(286720, 96256, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 110,
                name: "AD1 TRANSFER LOCK BT",
                inGameName: "Transfer Lock",
                archive: "ad1",
                modelPath: "ad1_model.bin",
                animationPath: "ad1_anim.bin",
                collisionPath: "ad1_collision.bin",
                texturePath: "ad1_tex.bin",
                entityPath: "ad1_Ent.bin",
                nodePath: "ad1_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(20, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 1,
                nodeLayer: 1,
                fogEnabled: false,
                clearFog: false,
                fogColor: new ColorRgb(29, 20, 10),
                fogSlope: 4,
                fogOffset: 65152,
                light1Color: new ColorRgb(29, 20, 10),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(7, 11, 15),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 5734400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-311296, -29196, -172032).ToFloatVector(),
                cameraMax: new Vector3Fx(331776, 131072, 126976).ToFloatVector(),
                playerMin: new Vector3Fx(-311296, -29196, -166907).ToFloatVector(),
                playerMax: new Vector3Fx(331776, 131072, 126976).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 111,
                name: "AD1 TRANSFER LOCK DM",
                inGameName: "Transfer Lock",
                archive: "unit2_RM4",
                modelPath: "unit2_rm4_model.bin",
                animationPath: "unit2_rm4_anim.bin",
                collisionPath: "unit2_rm4_collision.bin",
                texturePath: "unit2_rm4_tex.bin",
                entityPath: "ad1_dm1_Ent.bin",
                nodePath: "ad1_dm1_NODE.bin",
                roomNodeName: "rmGoal",
                battleTimeLimit: TimeLimit(20, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 1,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(29, 20, 10),
                fogSlope: 4,
                fogOffset: 65300,
                light1Color: new ColorRgb(29, 20, 10),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(7, 11, 15),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 3276800,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-294912, -12288, -172032).ToFloatVector(),
                cameraMax: new Vector3Fx(294912, 94208, 172032).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 112,
                name: "AD2 MAGMA VENTS",
                inGameName: "Council Chamber",
                archive: "ad2",
                modelPath: "ad2_model.bin",
                animationPath: "ad2_anim.bin",
                collisionPath: "ad2_collision.bin",
                texturePath: "ad2_tex.bin",
                entityPath: "ad2_Ent.bin",
                nodePath: "ad2_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(12, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 3,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(31, 24, 18),
                fogSlope: 5,
                fogOffset: 65200,
                light1Color: new ColorRgb(31, 24, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(13, 12, 7),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-278528, 0, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(245760, 147456, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 113,
                name: "AD2 ALINOS PERCH",
                inGameName: "Alinos Perch",
                archive: "unit1_RM2",
                modelPath: "unit1_rm2_model.bin",
                animationPath: "unit1_rm2_anim.bin",
                collisionPath: "unit1_rm2_collision.bin",
                texturePath: "unit1_rm2_tex.bin",
                entityPath: "ad2_dm1_Ent.bin",
                nodePath: "ad2_dm1_NODE.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(12, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 3,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(31, 24, 18),
                fogSlope: 5,
                fogOffset: 65200,
                light1Color: new ColorRgb(31, 24, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(13, 12, 7),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-278528, 0, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(245760, 159744, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 114,
                name: "UNIT1 ALINOS LANDFALL",
                inGameName: "Alinos Gateway",
                archive: "unit1_Land",
                modelPath: "unit1_land_model.bin",
                animationPath: "unit1_land_anim.bin",
                collisionPath: "unit1_land_collision.bin",
                texturePath: "unit1_land_tex.bin",
                entityPath: "Unit1_Land_dm1_Ent.bin",
                nodePath: "unit1_Land_dm1_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(40, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(31, 24, 18),
                fogSlope: 4,
                fogOffset: 65180,
                light1Color: new ColorRgb(31, 24, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(13, 12, 7),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 4915200,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-290816, 8192, -217088).ToFloatVector(),
                cameraMax: new Vector3Fx(348160, 86016, 241664).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 115,
                name: "UNIT2 LANDING BAY",
                inGameName: "Celestial Gateway",
                archive: "unit2_Land",
                modelPath: "unit2_Land_model.bin",
                animationPath: "unit2_Land_anim.bin",
                collisionPath: "unit2_Land_collision.bin",
                texturePath: "unit2_land_tex.bin",
                entityPath: "unit2_land_dm1_Ent.bin",
                nodePath: "unit2_land_dm1_NODE.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(40, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(18, 31, 18),
                fogSlope: 4,
                fogOffset: 65152,
                light1Color: new ColorRgb(24, 31, 24),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(7, 11, 15),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 5734400,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-94208, -45056, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(102400, 114688, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 116,
                name: "UNIT 3 VESPER STARPORT",
                inGameName: "VDO Gateway",
                archive: "unit3_Land",
                modelPath: "unit3_land_model.bin",
                animationPath: "unit3_land_anim.bin",
                collisionPath: "unit3_land_collision.bin",
                texturePath: "unit3_land_tex.bin",
                entityPath: "unit3_Land_dm1_Ent.bin",
                nodePath: "unit3_Land_dm1_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(40, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(24, 20, 31),
                fogSlope: 3,
                fogOffset: 65152,
                light1Color: new ColorRgb(18, 22, 30),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 8, 14),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-180224, -20480, -172032).ToFloatVector(),
                cameraMax: new Vector3Fx(172032, 118784, 172032).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 117,
                name: "UNIT 4 ARCTERRA BASE",
                inGameName: "Arcterra Gateway",
                archive: "unit4_Land",
                modelPath: "unit4_land_model.bin",
                animationPath: "unit4_land_anim.bin",
                collisionPath: "unit4_land_collision.bin",
                texturePath: "unit4_land_tex.bin",
                entityPath: "unit4_Land_dm1_Ent.bin",
                nodePath: "unit4_Land_dm1_node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(40, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(10, 14, 18),
                fogSlope: 6,
                fogOffset: 65300,
                light1Color: new ColorRgb(10, 14, 18),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(4, 4, 8),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-90112, -20480, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(122880, 155648, 106496).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 118,
                name: "Gorea Prison",
                inGameName: "Oubliette",
                archive: "Gorea_b2",
                modelPath: "gorea_b2_Model.bin",
                animationPath: "gorea_b2_Anim.bin",
                collisionPath: "Gorea_b2_collision.bin",
                texturePath: "gorea_b2_tex.bin",
                entityPath: "gorea_b2_dm_Ent.bin",
                nodePath: "gorea_b2_dm_NODE.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(40, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 100,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(16, 30, 25),
                fogSlope: 4,
                fogOffset: 65535,
                light1Color: new ColorRgb(18, 16, 14),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(27, 18, 9),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -286720,
                size: RoomSize.Large,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 119,
                name: "E3 FIRST HUNT",
                inGameName: "Stasis Bunker",
                archive: "e3Level",
                modelPath: "e3Level_Model.bin",
                animationPath: "e3Level_Anim.bin",
                collisionPath: "e3Level_Collision.bin",
                texturePath: "e3level_tex.bin",
                entityPath: "e3Level_Ent.bin",
                nodePath: "e3Level_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(12, 0, 0),
                timeLimit: TimeLimit(4, 0, 0),
                pointLimit: 3,
                nodeLayer: 1,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(24, 20, 31),
                fogSlope: 5,
                fogOffset: 65152,
                light1Color: new ColorRgb(24, 20, 31),
                light1Vector: new Vector3Fx(409, -4096, 0).ToFloatVector(),
                light2Color: new ColorRgb(9, 8, 14),
                light2Vector: new Vector3Fx(0, 4095, -409).ToFloatVector(),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.Medium,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 122,
                name: "biodefense chamber 06",
                inGameName: "Early Processor Core",
                archive: "unit1_b2",
                modelPath: "unit1_b2_model.bin",
                animationPath: "unit1_b2_anim.bin",
                collisionPath: "unit1_b2_collision.bin",
                texturePath: null,
                entityPath: null, // Unit1_b2_Ent is used in Cretaphid boss room
                nodePath: "unit1_b2_node.bin", // todo?
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: false,
                clearFog: false,
                fogColor: new ColorRgb(0, 0, 0),
                fogSlope: 0,
                fogOffset: 0,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(1f, 0f, 0f),
                light2Color: new ColorRgb(31, 31, 31),
                light2Vector: new Vector3(0f, -1f, 0f),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.None,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 123,
                name: "biodefense chamber 05",
                inGameName: "Early Stasis Bunker",
                archive: "unit2_b2",
                modelPath: "unit2_b2_model.bin",
                animationPath: "unit2_b2_anim.bin",
                collisionPath: "unit2_b2_collision.bin",
                texturePath: null,
                entityPath: null, // Unit2_b2_Ent is used in Slench boss room
                nodePath: null, // unit2_b2_node is used in Slench boss room
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: false,
                clearFog: false,
                fogColor: new ColorRgb(0, 0, 0),
                fogSlope: 0,
                fogOffset: 0,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(1f, 0f, 0f),
                light2Color: new ColorRgb(31, 31, 31),
                light2Vector: new Vector3(0f, -1f, 0f),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.None,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 124,
                name: "biodefense chamber 03",
                inGameName: "Early Head Shot",
                archive: "unit3_b1",
                modelPath: "unit3_b1_model.bin",
                animationPath: "unit3_b1_anim.bin",
                collisionPath: "unit3_b1_collision.bin",
                texturePath: null,
                entityPath: null, // Unit3_b1_Ent is used in Cretaphid boss room
                nodePath: "unit3_b1_node.bin", // todo?
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: false,
                clearFog: false,
                fogColor: new ColorRgb(0, 0, 0),
                fogSlope: 0,
                fogOffset: 0,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(1f, 0f, 0f),
                light2Color: new ColorRgb(31, 31, 31),
                light2Vector: new Vector3(0f, -1f, 0f),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.None,
                cameraMin: new Vector3Fx(-200704, 0, -200704).ToFloatVector(),
                cameraMax: new Vector3Fx(196608, 294912, 192512).ToFloatVector(), // y 48 to 72
                playerMin: new Vector3Fx(-286720, -86949, -286720).ToFloatVector(),
                playerMax: new Vector3Fx(286720, 294912, 286720).ToFloatVector(), // same as above
                multiplayer: true),
            new RoomMetadata(
                id: 125,
                name: "biodefense chamber 08",
                inGameName: "Early Fuel Stack",
                archive: "unit3_b2",
                modelPath: "unit3_b2_model.bin",
                animationPath: "unit3_b2_anim.bin",
                collisionPath: "unit3_b2_collision.bin",
                texturePath: null,
                entityPath: null, // Unit3_b2_Ent is used in Slench boss room
                nodePath: "unit3_b2_node.bin", // todo?
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: false,
                clearFog: false,
                fogColor: new ColorRgb(0, 0, 0),
                fogSlope: 0,
                fogOffset: 0,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(1f, 0f, 0f),
                light2Color: new ColorRgb(31, 31, 31),
                light2Vector: new Vector3(0f, -1f, 0f),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.None,
                cameraMin: new Vector3Fx(-94208, -118784, -110592).ToFloatVector(),
                cameraMax: new Vector3Fx(245760, 200704, 172032).ToFloatVector(), // x 41 to 60, y 30 to 49
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 126,
                name: "biodefense chamber 04",
                inGameName: "Early Sanctorus",
                archive: "unit4_b1",
                modelPath: "unit4_b1_model.bin",
                animationPath: "unit4_b1_anim.bin",
                collisionPath: "unit4_b1_collision.bin",
                texturePath: null,
                entityPath: null, // unit4_b1_Ent is used in Slench boss room
                nodePath: "unit4_b1_Node.bin", // todo: ?
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: false,
                clearFog: false,
                fogColor: new ColorRgb(0, 0, 0),
                fogSlope: 0,
                fogOffset: 0,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(1f, 0f, 0f),
                light2Color: new ColorRgb(31, 31, 31),
                light2Vector: new Vector3(0f, -1f, 0f),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.None,
                cameraMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                cameraMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                playerMin: new Vector3Fx(-1228800, -1228800, -1228800).ToFloatVector(),
                playerMax: new Vector3Fx(1228800, 1228800, 1228800).ToFloatVector(),
                multiplayer: true),
            new RoomMetadata(
                id: 127,
                name: "biodefense chamber 07",
                inGameName: "Early Sic Transit",
                archive: "unit4_b2",
                modelPath: "unit4_b2_model.bin",
                animationPath: "unit4_b2_anim.bin",
                collisionPath: "unit4_b2_collision.bin",
                texturePath: null,
                entityPath: null, // unit4_b2_Ent is used in Cretaphid boss room
                nodePath: "unit4_b2_Node.bin", // todo: ?
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: false,
                clearFog: false,
                fogColor: new ColorRgb(0, 0, 0),
                fogSlope: 0,
                fogOffset: 0,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(1f, 0f, 0f),
                light2Color: new ColorRgb(31, 31, 31),
                light2Vector: new Vector3(0f, -1f, 0f),
                farClip: 1638400,
                killHeight: -122880,
                size: RoomSize.SinglePlayer,
                multiplayer: true),
            new RoomMetadata(
                id: 0,
                name: "Level MP1",
                inGameName: "Trooper Module",
                archive: "mp1",
                modelPath: "mp1_Model.bin",
                animationPath: "mp1_Anim.bin",
                collisionPath: "mp1_Collision.bin",
                texturePath: null,
                entityPath: "mp1_Ent.bin",
                nodePath: "mp1_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: true,
                clearFog: true,
                fogColor: new ColorRgb(31, 31, 31),
                fogSlope: 2,
                fogOffset: 65152,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(0.25f, -0.5f, -0.25f),
                light2Color: new ColorRgb(4, 4, 16),
                light2Vector: new Vector3(0, 1, -0.25f),
                farClip: 368640,
                killHeight: 0,
                size: RoomSize.SinglePlayer,
                multiplayer: true,
                firstHunt: true),
            new RoomMetadata(
                id: 1,
                name: "Level MP2",
                inGameName: "Assault Cradle",
                archive: "mp2",
                modelPath: "mp2_Model.bin",
                animationPath: "mp2_Anim.bin",
                collisionPath: "mp2_Collision.bin",
                texturePath: null,
                entityPath: "mp2_Ent.bin",
                nodePath: "mp2_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: true,
                clearFog: true,
                fogColor: new ColorRgb(6, 12, 11),
                fogSlope: 5,
                fogOffset: 64900,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(0.25f, -0.5f, -0.25f),
                light2Color: new ColorRgb(4, 4, 16),
                light2Vector: new Vector3(0, 1, -0.25f),
                farClip: 245760,
                killHeight: 0,
                size: RoomSize.SinglePlayer,
                multiplayer: true,
                firstHunt: true),
            new RoomMetadata(
                id: 2,
                name: "Level MP3",
                inGameName: "Ancient Vestige",
                archive: "mp3",
                modelPath: "mp3_Model.bin",
                animationPath: "mp3_Anim.bin",
                collisionPath: "mp3_Collision.bin",
                texturePath: null,
                entityPath: "mp3_Ent.bin",
                nodePath: "mp3_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(29, 26, 20),
                fogSlope: 4,
                fogOffset: 65152,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(0.25f, -0.5f, -0.25f),
                light2Color: new ColorRgb(4, 4, 16),
                light2Vector: new Vector3(0, 1, -0.25f),
                farClip: 81920000,
                killHeight: 0,
                size: RoomSize.SinglePlayer,
                multiplayer: true,
                firstHunt: true),
            new RoomMetadata(
                id: 7,
                name: "Level MP5",
                inGameName: "Early Head Shot (First Hunt)",
                archive: "mp5",
                modelPath: "mp5_Model.bin",
                animationPath: "mp5_Anim.bin",
                collisionPath: "mp5_Collision.bin",
                texturePath: null,
                entityPath: "mp5_Ent.bin",
                nodePath: "mp5_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(8, 16, 31),
                fogSlope: 5,
                fogOffset: 65152,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(0.25f, -0.5f, -0.25f),
                light2Color:  new ColorRgb(4, 4, 16),
                light2Vector: new Vector3(0, 1, -0.25f),
                farClip: 245760,
                killHeight: 0,
                size: RoomSize.SinglePlayer,
                multiplayer: true,
                firstHunt: true),
            new RoomMetadata(
                id: 8,
                name: "Level MP1b", // copy of Level MP1 with a few different params and no name string
                inGameName: "Trooper Module",
                archive: "mp1",
                modelPath: "mp1_Model.bin",
                animationPath: "mp1_Anim.bin",
                collisionPath: "mp1_Collision.bin",
                texturePath: null,
                entityPath: "mp1_Ent.bin",
                nodePath: "mp1_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(8, 16, 31),
                fogSlope: 5,
                fogOffset: 65152,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(0.25f, -0.5f, -0.25f),
                light2Color:  new ColorRgb(4, 4, 16),
                light2Vector: new Vector3(0, 1, -0.25f),
                farClip: 245760,
                killHeight: 0,
                size: RoomSize.SinglePlayer,
                multiplayer: true,
                firstHunt: true),
            new RoomMetadata(
                id: 9,
                name: "E3 level",
                inGameName: "Stasis Bunker (First Hunt)",
                archive: "e3Level",
                modelPath: "e3Level_Model.bin",
                animationPath: "e3Level_Anim.bin",
                collisionPath: "e3Level_Collision.bin",
                texturePath: null,
                entityPath: "e3Level_Ent.bin",
                nodePath: "e3Level_Node.bin",
                roomNodeName: null,
                battleTimeLimit: TimeLimit(10, 0, 0),
                timeLimit: TimeLimit(2, 0, 0),
                pointLimit: 0,
                nodeLayer: 0,
                fogEnabled: true,
                clearFog: false,
                fogColor: new ColorRgb(8, 16, 31),
                fogSlope: 5,
                fogOffset: 65152,
                light1Color: new ColorRgb(31, 31, 31),
                light1Vector: new Vector3(0.25f, -0.5f, -0.25f),
                light2Color: new ColorRgb(4, 4, 16),
                light2Vector: new Vector3(0, 1, -0.25f),
                farClip: 245760,
                killHeight: 0,
                size: RoomSize.SinglePlayer,
                multiplayer: true,
                firstHunt: true)
        };

        public static IReadOnlyList<RoomMetadata> RoomList
            => RuntimeRooms.Snapshot.Rooms.Select(room => room.Metadata).ToArray();

        public static FrozenDictionary<string, RoomMetadata> RoomMetadata
            => RuntimeRooms.Snapshot.ByName.Values.ToFrozenDictionary(
                room => room.RoomKey, room => room.Metadata,
                StringComparer.OrdinalIgnoreCase);

        internal static Mods.MapGen.RuntimeRoomRegistry RuntimeRooms
        {
            get
            {
                Mods.MapGen.RuntimeRoomRegistry rooms = Mods.MapGen.CustomRooms.RuntimeRooms;
                rooms.EnsureBuiltIns(_baseRoomIds, BaseRoomList);
                return rooms;
            }
        }

        public static readonly FrozenDictionary<int, string> CtfNodeDataOverrides = Frozen.Create<int, string>(
        [
            new( 93, @"levels\nodeData\mp1_CTF_node.bin"),    // MP1 SANCTORUS (Data Shrine)
            new( 99, @"levels\nodeData\mp6_CTF_node.bin"),    // MP6 HEADSHOT (Head Shot)
            new(101, @"levels\nodeData\mp8_CTF_node.bin"),    // MP8 FIRE CONTROL (Weapons Complex)
            new(102, @"levels\nodeData\mp9_CTF_node.bin"),    // MP9 CRYOCHASM (Ice Hive)
            new(105, @"levels\nodeData\mp12_CTF_node.bin"),   // MP12 SIC TRANSIT (Sic Transit)
            new(107, @"levels\nodeData\mp14_CTF_node.bin"),   // MP14 OUTER REACH (Outer Reach)
            new(108, @"levels\nodeData\ctf1_CTF_node.bin"),   // CTF1 FAULT LINE - EXPANDED (Fault Line)
            new(119, @"levels\nodeData\e3Level_CTF_Node.bin") // E3 FIRST HUNT (Stasis Bunker)
        ]);
    }
}
