// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MphRead.Backend.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MphRead.Backend.Data.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    [Migration("20260907171057_RatingLedger")]
    partial class RatingLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Data.CareerProjectionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("RebuildRequired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("career_projection_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RebuildRequired = true
                        });
                });

            modelBuilder.Entity("MphRead.Backend.Data.HunterAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Data.HunterLicense", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingPoints")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("hunter_licenses", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Data.PlayerProfile", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte>("FavoriteHunter")
                        .HasColumnType("smallint");

                    b.HasKey("PlayerId");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Matches.AcceptedMatch", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CareerEligible")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<byte[]>("OriginalReport")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ProcessingOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProcessingOrder"));

                    b.Property<int?>("RatingIneligibilityReason")
                        .HasColumnType("integer");

                    b.Property<int>("RatingPolicyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("RatingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerIncarnation")
                        .HasColumnType("uuid");

                    b.Property<int>("TrustClass")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.HasIndex("ProcessingOrder")
                        .IsUnique();

                    b.ToTable("accepted_matches", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Matches.CareerAggregate", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrustClass")
                        .HasColumnType("integer");

                    b.Property<string>("Dimension")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("AltFormKills")
                        .HasColumnType("bigint");

                    b.Property<long>("Assists")
                        .HasColumnType("bigint");

                    b.Property<long?>("BipedKills")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentWinStreak")
                        .HasColumnType("bigint");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint");

                    b.Property<long>("Deaths")
                        .HasColumnType("bigint");

                    b.Property<long>("HeadshotKills")
                        .HasColumnType("bigint");

                    b.Property<long>("Kills")
                        .HasColumnType("bigint");

                    b.Property<long>("KillsAsPrime")
                        .HasColumnType("bigint");

                    b.Property<long>("LongestKillStreak")
                        .HasColumnType("bigint");

                    b.Property<long>("LongestWinStreak")
                        .HasColumnType("bigint");

                    b.Property<long>("Losses")
                        .HasColumnType("bigint");

                    b.Property<long>("Matches")
                        .HasColumnType("bigint");

                    b.Property<long>("NodesCaptured")
                        .HasColumnType("bigint");

                    b.Property<long>("OctolithScores")
                        .HasColumnType("bigint");

                    b.Property<long>("OutcomeSamples")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayedTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("Ties")
                        .HasColumnType("bigint");

                    b.Property<long>("Wins")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "TrustClass", "Dimension", "Key");

                    b.HasIndex("TrustClass", "Dimension", "Kills", "PlayerId");

                    b.HasIndex("TrustClass", "Dimension", "Wins", "PlayerId");

                    b.ToTable("career_aggregates", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Matches.CareerParticipation", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("Assists")
                        .HasColumnType("bigint");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint");

                    b.Property<long>("Deaths")
                        .HasColumnType("bigint");

                    b.Property<bool>("Eligible")
                        .HasColumnType("boolean");

                    b.Property<long>("Kills")
                        .HasColumnType("bigint");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<long>("PlayedTicks")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessingOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("Tied")
                        .HasColumnType("boolean");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId", "ProcessingOrder");

                    b.ToTable("career_participations", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Matches.RatingLedgerEntry", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("AppliedDelta")
                        .HasColumnType("integer");

                    b.Property<int>("NormalizedDelta")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentCount")
                        .HasColumnType("integer");

                    b.Property<int>("PointsAfter")
                        .HasColumnType("integer");

                    b.Property<int>("PointsBefore")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ProcessingOrder")
                        .HasColumnType("bigint");

                    b.Property<int>("RawDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TierAfter")
                        .HasColumnType("integer");

                    b.Property<int>("TierBefore")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId", "ProcessingOrder")
                        .IsUnique();

                    b.ToTable("rating_transactions", (string)null);
                });

            modelBuilder.Entity("MphRead.Backend.Matches.RatingPairLedgerEntry", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OpponentPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentPointsBefore")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentTierBefore")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "PlayerId", "OpponentPlayerId");

                    b.ToTable("rating_pair_contributions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MphRead.Backend.Data.HunterAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MphRead.Backend.Data.HunterAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MphRead.Backend.Data.HunterAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MphRead.Backend.Data.HunterAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MphRead.Backend.Data.HunterLicense", b =>
                {
                    b.HasOne("MphRead.Backend.Data.HunterAccount", null)
                        .WithOne()
                        .HasForeignKey("MphRead.Backend.Data.HunterLicense", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MphRead.Backend.Data.PlayerProfile", b =>
                {
                    b.HasOne("MphRead.Backend.Data.HunterAccount", null)
                        .WithOne()
                        .HasForeignKey("MphRead.Backend.Data.PlayerProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MphRead.Backend.Matches.CareerAggregate", b =>
                {
                    b.HasOne("MphRead.Backend.Data.HunterLicense", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MphRead.Backend.Matches.CareerParticipation", b =>
                {
                    b.HasOne("MphRead.Backend.Matches.AcceptedMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MphRead.Backend.Data.HunterLicense", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MphRead.Backend.Matches.RatingLedgerEntry", b =>
                {
                    b.HasOne("MphRead.Backend.Matches.AcceptedMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MphRead.Backend.Data.HunterLicense", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MphRead.Backend.Matches.RatingPairLedgerEntry", b =>
                {
                    b.HasOne("MphRead.Backend.Matches.RatingLedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("MatchId", "PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
