<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/MphRead/Mods/Launcher/RmlUi/Host/*.cs" Exclude="../../src/MphRead/Mods/Launcher/RmlUi/Host/RmlUiLobbyBindings.cs" Link="Host/%(Filename)%(Extension)" />
    <Compile Include="../../src/MphRead/Mods/Launcher/Portable/RmlUiPointerMapping.cs" Link="RmlUiPointerMapping.cs" />
  </ItemGroup>
</Project>
