using System;
using System.Linq;
using MphRead.Mods.MatchEvents;
int checks = 0;
void Check(bool value, string name) { if (!value) throw new Exception(name); checks++; }
var a = new MatchSemanticActor(0, 1, 1);
var b = new MatchSemanticActor(1, 1, 1);
var bus = new MatchSemanticEventBus(); bus.Begin(1, 1);
MatchSemanticEvent Kill(uint id, uint tick, MatchSemanticActor? actor = null, MatchSemanticEventFlags flags = 0)
    => new(id, 1, 1, tick, MatchSemanticEventType.PlayerKilled, actor ?? a, b with { Life = (ushort)Math.Min(id, ushort.MaxValue) }, Flags: flags);
Check(bus.Accept(Kill(1, 1)), "first kill");
Check(!bus.Accept(Kill(1, 1)), "duplicate");
Check(bus.Awards.Awards.Single().Kind == MatchAwardKind.FirstBlood, "first blood once");
Check(!bus.Accept(Kill(2, 2) with { Target = b }), "same life new event id rejected");
Check(!bus.Accept(Kill(2, 2) with { Target = MatchSemanticActor.None }), "impossible kill identity");
Check(bus.Accept(Kill(2, 241)), "inclusive four seconds");
Check(bus.Awards.Awards.Last().Kind == MatchAwardKind.DoubleKill, "boundary double");
bus.Accept(Kill(3, 482));
Check(bus.Awards.Awards.Count == 2, "outside boundary resets");
Check(!bus.Accept(Kill(4, 481)), "backwards tick");
Check(!bus.Accept(Kill(4, 483) with { Actor = new(0, 0, 1) }), "invalid generation");
Check(!bus.Accept(Kill(4, 483) with { AuthorityEpoch = 2 }), "cross epoch");
bus.Accept(Kill(4, 483, new(0, 2, 1)));
Check(bus.Awards.Awards.Count == 2, "slot reuse resets chain");
bus.Accept(Kill(5, 484) with { Actor = b, Target = new(0, 2, 1) });
bus.Accept(Kill(6, 485, new(0, 2, 2)));
Check(bus.Awards.Awards.Count == 2, "death and new life reset chain");
bus.Accept(Kill(7, 486, flags: MatchSemanticEventFlags.FriendlyFire));
Check(bus.Awards.Awards.Count == 2, "team kills excluded");
bus.Begin(2, 2);
Check(bus.Events.Count == 0 && bus.Awards.Awards.Count == 0, "epoch reset");
for (uint i = 1; i <= 2000; i++)
{
    bus.Accept(Kill(i, i) with { MatchId = 2, AuthorityEpoch = 2 });
    if (i == 30) Check(bus.Awards.Awards.Any(x => x.Kind == MatchAwardKind.Invincible), "thirty kill spree");
}
Check(bus.Events.Count == MatchSemanticEventBus.Capacity, "bounded history");
Check(!bus.Accept(Kill(1, 2001) with { MatchId = 2, AuthorityEpoch = 2 }), "eviction preserves dedup");
Check(bus.Awards.Awards.Count <= MatchSemanticEventBus.Capacity, "bounded awards");
bus.Accept(Kill(uint.MaxValue, 2001) with { MatchId = 2, AuthorityEpoch = 2 });
Check(!bus.TryEmit(2002, MatchSemanticEventType.MatchEnded, a, b), "id exhaustion fails closed");
bus.Begin(2, 3);
Check(bus.TryEmit(1, MatchSemanticEventType.MatchStarted, MatchSemanticActor.None, MatchSemanticActor.None), "explicit epoch rollover");
Check(bus.Events.Single().EventId == 1, "rollover starts one");
var tracker = new MatchAssistTracker();
var c = new MatchSemanticActor(2, 1, 1);
Span<MatchSemanticActor> contributors = stackalloc MatchSemanticActor[8];
tracker.Damage(a, b, 1, 10, true); tracker.Damage(a, b, 1, 10, true);
tracker.Damage(c, b, 2, 10, true);
Check(tracker.Collect(b, c, 301, contributors) == 1 && contributors[0] == a, "assist exact 300 inclusive and multihit dedup");
Check(tracker.Collect(b, c, 301, contributors) == 0, "assist death dedup");
tracker.Damage(a, b, 1, 10, true);
Check(tracker.Collect(b, c, 302, contributors) == 0, "assist 301 expired");
tracker.Damage(a, b, 1, 10, true);
Check(tracker.Collect(b with { Life = 2 }, c, 2, contributors) == 0, "victim life fencing");
tracker.Spawn(b with { Life = 2 });
Check(tracker.Collect(b with { Life = 2 }, c, 2, contributors) == 0, "spawn clears contributions");
tracker.Damage(a, b, 1, 0, true); tracker.Damage(c, b, 1, 10, false); tracker.Damage(b, b, 1, 10, true);
Check(tracker.Collect(b, MatchSemanticActor.None, 2, contributors) == 0, "zero self friendly damage excluded");
tracker.Damage(a, b, 1, 10, true);
Check(tracker.Collect(b, a with { Life = 2 }, 2, contributors) == 0, "killer excluded across respawn");
tracker.Damage(a, b, 1, 10, true); tracker.Damage(a with { SlotGeneration = 2 }, b, 2, 10, true);
Check(tracker.Collect(b, c, 3, contributors) == 1 && contributors[0].SlotGeneration == 2, "contributor slot reuse");
tracker.Damage(a, b, 1, 10, true);
Check(tracker.Collect(b with { SlotGeneration = 2 }, c, 2, contributors) == 0, "victim slot reuse");
tracker.Reset();
Check(tracker.Collect(b, c, 2, contributors) == 0, "match clears assists");
var parity = new MatchSemanticParity();
parity.Semantic(Kill(1, 1)); parity.Legacy(2, MatchSemanticEventType.PlayerKilled, a, b, -1, false);
Check(parity.Matched == 1 && parity.Pending == 0, "independent delayed legacy match");
parity.Legacy(3, MatchSemanticEventType.PlayerKilled, a, b, -1, false);
Check(parity.MissingSemantic == 1, "independent missing semantic");
parity.Semantic(Kill(2, 4)); parity.Advance(125);
Check(parity.MissingLegacy == 1 && parity.Pending == 0, "independent missing legacy");
var scene = new MphRead.Scene();
var producer = new SceneMatchEvents();
var shooter = new MphRead.Entities.PlayerEntity { SlotIndex = 0 };
var victim = new MphRead.Entities.PlayerEntity { SlotIndex = 1 };
var helper = new MphRead.Entities.PlayerEntity { SlotIndex = 2 };
MphRead.Mods.Network.NetSession.Active = true;
producer.Spawn(scene, shooter); producer.Headshot(scene, shooter, victim, MphRead.BeamType.PowerBeam);
producer.Damage(scene, helper, victim, 10); producer.Death(scene, shooter, victim, MphRead.BeamType.PowerBeam, 0);
Check(producer.Bus.Events.Count == 0, "online client cannot author facts or assists");
MphRead.Mods.Network.NetSession.IsAuthority = true;
scene.Services.IsReplica = true;
producer.Spawn(scene, shooter); producer.Damage(scene, helper, victim, 10);
producer.Death(scene, shooter, victim, MphRead.BeamType.PowerBeam, 0);
Check(producer.Bus.Events.Count == 0, "replica cannot author facts or assists");
scene.Services.IsReplica = false;
producer.ObservePhase(scene);
producer.Spawn(scene, shooter); producer.Spawn(scene, victim); producer.Spawn(scene, helper);
producer.Damage(scene, helper, victim, 10);
MphRead.Mods.Network.NetSession.NetFrame = 300;
producer.Death(scene, shooter, victim, MphRead.BeamType.PowerBeam, 0);
Check(producer.Bus.Events.Count(e => e.Type == MatchSemanticEventType.PlayerAssisted) == 1, "authority emits five second assist");
producer.Death(scene, shooter, victim, MphRead.BeamType.PowerBeam, 0);
Check(producer.Bus.Events.Count(e => e.Type == MatchSemanticEventType.PlayerKilled) == 1, "authority death once per life");
MphRead.Mods.Network.NetSession.AuthorityEpoch = 2;
MphRead.Mods.Network.NetSession.NetFrame = 0;
producer.Spawn(scene, victim); producer.Damage(scene, helper, victim, 10);
MphRead.Mods.Network.NetPlayerLifecycle.Generations[2] = 2;
producer.Death(scene, shooter, victim, MphRead.BeamType.PowerBeam, 0);
Check(producer.Bus.Events.All(e => e.Type != MatchSemanticEventType.PlayerAssisted), "reused contributor cannot receive old assist");
MphRead.Mods.Network.NetSession.Active = false;
var local = new SceneMatchEvents(); local.Spawn(scene, victim); local.Damage(scene, helper, victim, 10);
scene.FrameCount = 300;
local.Death(scene, shooter, victim, MphRead.BeamType.PowerBeam, 0);
Check(local.Bus.Events.Any(e => e.Type == MatchSemanticEventType.PlayerAssisted), "offline emits assist from simulation frame");
local.Spawn(scene, victim);
Check(local.Bus.Events.Last().Actor.Life == 2, "offline respawn life");
var newVictim = new MphRead.Entities.PlayerEntity { SlotIndex = 1 };
local.Spawn(scene, newVictim);
Check(local.Bus.Events.Last().Actor.SlotGeneration == 2 && local.Bus.Events.Last().Actor.Life == 1, "offline slot reuse");
local.ResetMatch(scene); scene.FrameCount = 0; local.ObservePhase(scene);
Check(local.Bus.Events.Single().Type == MatchSemanticEventType.MatchStarted && local.Bus.Awards.Awards.Count == 0, "offline match reset");
Console.WriteLine($"PASS {checks} semantic event checks (F0, content-free)");
