#!/usr/bin/env python3
"""Check gradual build/source guardrails for Project Prime.

This guard intentionally checks architecture-sensitive boundaries, not a
repository-wide style policy.  Existing style debt therefore remains
advisory; package version drift and authoritative hot-path boundary violations
are reported with a concrete file and line.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET


PACKAGE_RE = re.compile(r"PackageReference", re.IGNORECASE)
VERSION_RE = re.compile(r"\bVersion\s*=")
BLOCKING_RE = re.compile(
    r"\.Result\b|\.Wait\s*\(|GetAwaiter\s*\(\)\s*\.\s*GetResult\s*\(\)|"
    r"\bThread\s*\.\s*Sleep\s*\(")
LINQ_RE = re.compile(
    r"(?<!Math)(?<!MathF)(?<!Single)(?<!Double)(?<!Decimal)\.(?:Where|Select|ToArray|ToList|GroupBy|OrderBy|ThenBy|Distinct|"
    r"Any|Count|First|Single|Sum|Max|Min)\s*\(")
DB_RE = re.compile(r"\b(?:DbContext|DbSet|Npgsql|EntityFrameworkCore|UseNpgsql)\b")
FACADE_RE = re.compile(r"\bCustomRooms\s*\.")

HOT_PATH_ROOTS = (Path("src/Game/Gameplay"), Path("src/Game/World"),
                  Path("src/Server.Worker/Simulation"))
FACADE_ROOTS = (Path("src/Game/Gameplay"), Path("src/Game/World"),
                Path("src/Server.Worker"), Path("src/Server.Node"))
DB_ROOTS = (Path("src/Game"), Path("src/Server.Node"), Path("src/Server.Worker"),
            Path("src/Client"))

# These are intentional pre-existing seams. They remain visible in the report
# and should be retired as the owning service boundaries move; a new source
# file cannot silently add another exception.
KNOWN_BLOCKING = {
    "src/Server.Worker/Simulation/FixedTickScheduler.cs",
    "src/Server.Worker/Simulation/SimulationLane.cs",
}
KNOWN_HOT_LINQ = {
    "src/Server.Worker/Simulation/ServerSimulation.cs",
    "src/Server.Worker/Simulation/SimulationLane.cs",
    "src/Server.Worker/Simulation/SimulationLaneManager.cs",
    "src/Game/Gameplay/Hunters/PlayerAi.cs",
}
KNOWN_FACADE = {
    "src/Server.Worker/Program.cs",
    "src/Server.Worker/Networking/ServerContentValidation.cs",
    "src/Server.Worker/Maps/WorkerMapBuildService.cs",
}


def _normalize_line(line: str) -> str:
    return " ".join(line.split())


def _load_baseline(root: Path) -> set[tuple[str, str, str]]:
    path = root / "tools" / "build-guardrails-baseline.json"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()
    entries = payload.get("entries", [])
    return {
        (entry["kind"], entry["path"], _normalize_line(entry["text"]))
        for entry in entries
        if isinstance(entry, dict)
        and isinstance(entry.get("kind"), str)
        and isinstance(entry.get("path"), str)
        and isinstance(entry.get("text"), str)
    }


def _is_baselined(baseline: set[tuple[str, str, str]], kind: str,
                  relative: str, line: str) -> bool:
    return (kind, relative, _normalize_line(line)) in baseline


def _relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _cs_files(root: Path, prefixes: tuple[Path, ...]):
    for prefix in prefixes:
        directory = root / prefix
        if not directory.is_dir():
            continue
        yield from sorted(path for path in directory.rglob("*.cs")
                          if not {"obj", "bin"}.intersection(path.parts))


def check_packages(root: Path) -> list[str]:
    errors: list[str] = []
    central = root / "Directory.Packages.props"
    if not central.is_file():
        return ["Directory.Packages.props: central package management file is missing"]
    try:
        central_root = ET.parse(central).getroot()
    except ET.ParseError as error:
        return [f"Directory.Packages.props: invalid XML: {error}"]
    versions: dict[str, str] = {}
    for item in central_root.iter("PackageVersion"):
        name = item.attrib.get("Include", "")
        version = item.attrib.get("Version", "")
        if not name or not version:
            errors.append("Directory.Packages.props: every PackageVersion needs Include and Version")
        elif name in versions:
            errors.append(f"Directory.Packages.props: duplicate PackageVersion {name}")
        else:
            versions[name] = version
    for project in sorted(root.rglob("*.csproj")):
        # artifacts/ may contain ephemeral scratch projects generated by a
        # validation run. They are not repository projects and can carry their
        # own isolated package metadata; never let them block the source tree
        # guard (or turn an ignored fixture into a tracked migration).
        if {"artifacts", "obj", "bin"}.intersection(project.relative_to(root).parts):
            continue
        try:
            project_root = ET.parse(project).getroot()
        except ET.ParseError as error:
            errors.append(f"{_relative(root, project)}: invalid XML: {error}")
            continue
        for item in project_root.iter("PackageReference"):
            name = item.attrib.get("Include", "")
            if not name:
                errors.append(f"{_relative(root, project)}: PackageReference is missing Include")
                continue
            if VERSION_RE.search(" ".join(f"{key}={value}" for key, value in item.attrib.items())):
                errors.append(f"{_relative(root, project)}: package {name} has an inline Version; use Directory.Packages.props")
            if name not in versions:
                errors.append(f"{_relative(root, project)}: package {name} has no central PackageVersion")
    return errors


def _source_errors(root: Path, *, source_only: bool = True) -> list[str]:
    errors: list[str] = []
    baseline = _load_baseline(root)
    for path in _cs_files(root, HOT_PATH_ROOTS):
        relative = _relative(root, path)
        for line_number, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
            if (BLOCKING_RE.search(line)
                    and relative not in KNOWN_BLOCKING
                    and not _is_baselined(baseline, "blocking", relative, line)):
                if "Scene.Match.Result" in line:
                    continue
                errors.append(f"{relative}:{line_number}: blocking operation in authoritative hot path")
            if (LINQ_RE.search(line)
                    and relative not in KNOWN_HOT_LINQ
                    and not _is_baselined(baseline, "hot-linq", relative, line)):
                errors.append(f"{relative}:{line_number}: LINQ allocation/query in authoritative hot path")
    for path in _cs_files(root, FACADE_ROOTS):
        relative = _relative(root, path)
        if relative in KNOWN_FACADE:
            continue
        for line_number, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
            if FACADE_RE.search(line):
                errors.append(f"{relative}:{line_number}: CustomRooms global facade used outside its boundary")
    for path in _cs_files(root, DB_ROOTS):
        relative = _relative(root, path)
        for line_number, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
            if DB_RE.search(line):
                errors.append(f"{relative}:{line_number}: database dependency crosses the control-plane boundary")
    return errors


def inspect(root: Path, *, packages: bool = True, source: bool = True) -> list[str]:
    root = root.resolve()
    errors: list[str] = []
    if packages:
        errors.extend(check_packages(root))
        props = root / "Directory.Build.props"
        if not props.is_file():
            errors.append("Directory.Build.props: root analyzer properties are missing")
        else:
            text = props.read_text(encoding="utf-8-sig")
            if not re.search(r"<EnableNETAnalyzers[^>]*>\s*true\s*</EnableNETAnalyzers>", text):
                errors.append("Directory.Build.props: EnableNETAnalyzers must be enabled at the root")
            if not re.search(r"<EnforceCodeStyleInBuild[^>]*>\s*false\s*</EnforceCodeStyleInBuild>", text):
                errors.append("Directory.Build.props: code-style enforcement must remain advisory during migration")
    if source:
        errors.extend(_source_errors(root))
    return sorted(set(errors))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--packages-only", action="store_true")
    parser.add_argument("--source-only", action="store_true")
    args = parser.parse_args()
    packages = not args.source_only
    source = not args.packages_only
    try:
        errors = inspect(args.root, packages=packages, source=source)
    except (OSError, ValueError, ET.ParseError) as error:
        print(f"build guardrails: {error}", file=sys.stderr)
        return 2
    for error in errors:
        print(error)
    print(f"build guardrails: {len(errors)} violation(s)")
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())
