<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MphRead</RootNamespace>
    <AssemblyName>ProjectPrime.MapPlatform</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType Condition="'$(PrimeProtectClient)' != 'true'">embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Game/Game.csproj" />
  </ItemGroup>
</Project>
